name: Test and Deploy

on:
  push:
    branches: [ 'main', 'cicd' ]

jobs:
  deploy-test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: Copy ENV Laravel Configuration for CI
        run: php -r "file_exists('.env') || copy('.github/envs/general.env', '.env');"
      - name: Install Dependencies (PHP vendors)
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
      - name: Create DB
        run: |
          touch database/database.sqlite
          touch database/test.sqlite
      - name: Generate key
        run: php artisan key:generate
      - name: Migrate the database
        run: php artisan migrate
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        run: vendor/bin/phpunit
  #  db-test:
  #    services:
  #      mysql:
  #        image: mysql:5.7
  #        env:
  #          MYSQL_ALLOW_EMPTY_PASSWORD: YES
  #          MYSQL_DATABASE: laravel
  #          MYSQL_ROOT_PASSWORD: password
  #        ports:
  #          - 3306
  #        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
  #    runs-on: ubuntu-20.04
  #    steps:
  #      - uses: actions/checkout@v2
  #      - name: Copy ENV Laravel Configuration for CI
  #        run: php -r "file_exists('.env') || copy('.github/envs/mysql.env', '.env');"
  #      - name: Install Dependencies (PHP vendors)
  #        run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
  #      - name: Generate key
  #        run: php artisan key:generate
  #      - name: Migrate the database
  #        run: php artisan migrate
  #      - name: Rollback migrations to check backward compability
  #        run: php artisan migrat:rollback
  deploy:
    needs: [deploy-test]
    runs-on: ubuntu-20.04
    steps:
      - uses: fifsky/ssh-action@master
        with:
          command: |
            cd /var/www/rezer.nl
            php artisan down --render="errors::503"
            git reset --hard
            git pull
            composer install --optimize-autoloader --no-dev
            php artisan migrate --force
            php artisan cache:clear
            php artisan config:cache
            php artisan route:cache
            php artisan view:clear
            php artisan up
          host: ${{ secrets.SSH_HOST }}
          user: ${{ secrets.SSH_USER }}
          pass: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
