name: Test and Deploy

on:
  push:
    branches: [ 'main', 'cicd' ]

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: fifsky/ssh-action@master
        with:
          command: |
            cd /var/www/rezer.nl
            php artisan down --render="errors::503"
            git reset --hard
            git pull
            composer install --optimize-autoloader --no-dev
            php artisan migrate --force
            npm run prod
            php artisan cache:clear
            php artisan config:cache
            php artisan route:cache
            php artisan view:clear
            php artisan up
          host: ${{ secrets.SSH_HOST }}
          user: ${{ secrets.SSH_USER }}
          pass: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
